FROM nginx:1.19-alpine

RUN apk --no-cache --update add bash openssl

COPY default.conf.template /etc/nginx/templates/

# TODO this does not work
COPY nginx-proxy-reloading-script.sh /docker-entrypoint.d/nginx-proxy-reloading-script.sh
